const weaponParts = {
    BUTT: {
        ONE: "butt_1",
        TWO: "butt_2",
        THREE: "butt_3",
        FOUR: "butt_4",
        FIVE: "butt_5",
        SIX: "butt_6",
        SEVEN: "butt_7",
        EIGHT: "butt_8",
        NINE: "butt_9",
        TEN: "butt_10",
        ELEVEN: "butt_11",
        TWELVE: "butt_12",
        THIRTEEN: "butt_13",
        FOURTEEN: "butt_14",
        FIFTEEN: "butt_15"
    },
    HANDLE: {
        ONE: "handle_1",
        TWO: "handle_2",
        THREE: "handle_3",
        FOUR: "handle_4",
        FIVE: "handle_5",
        SIX: "handle_6",
        SEVEN: "handle_7",
        EIGHT: "handle_8",
        NINE: "handle_9",
        TEN: "handle_10",
        ELEVEN: "handle_11",
        TWELVE: "handle_12",
        THIRTEEN: "handle_13",
        FOURTEEN: "handle_14",
        FIFTEEN: "handle_15"
    },
    CANON: {
        ONE: "canon_1",
        TWO: "canon_2",
        THREE: "canon_3",
        FOUR: "canon_4",
        FIVE: "canon_5",
        SIX: "canon_6",
        SEVEN: "canon_7",
        EIGHT: "canon_8",
        NINE: "canon_9",
        TEN: "canon_10",
        ELEVEN: "canon_11",
        TWELVE: "canon_12",
        THIRTEEN: "canon_13",
        FOURTEEN: "canon_14",
        FIFTEEN: "canon_15"
    }
}